### ISSUE TITLE
npm包安装运行报错

### ISSUE THREAD

**Issue by EmperorHe** [zero2one3/markdown-editor-reactjs#2]
Module not found: Can't resolve '@ant-design/icons' in 'D:\work-space\front\react-project\md-editor-react\node_modules\_markdown-editor-reactjs@1.1.0@markdown-editor-reactjs\lib'
报错代码如上，不知道是不是我没装antd的缘故，这个工具依赖antd的图标库吗

**Comment by zero2one3** [comment]
抱歉，我的过错，立马修复。如果你急用，可以通过安装它未检测到三方库来解决。

**Comment by zero2one3** [comment]
@He-Huang 已经解决了，你看一下
