### ISSUE TITLE
哈哈哈 01

### ISSUE THREAD

**Issue by flightmakers** [zero2one3/markdown-editor-reactjs#3]
到了01的Github, 不知道说什么, 打个卡吧!

(你的文章总阅读量 还不如 zhangxinxu.com 一篇的阅读量呢QwQ....

**Comment by flightmakers** [comment]
哈哈哈

**Comment by zero2one3** [comment]
鑫旭大佬就是很厉害的呀~  哈哈比不过比不过

**Comment by flightmakers** [comment]
不过其实我更喜欢 ruanyifeng.com, 阮一峰的文风更朴实易懂, 不像zxx的文风花里胡哨的一批, 一篇文章有一般都是语气词和废话
